FROM node:22-alpine

WORKDIR /usr/src/app

# Установка зависимостей
COPY package.json yarn.lock ./
RUN corepack enable && \
    yarn set version stable && \
    yarn install --network-timeout 1000000

# Копирование исходного кода
COPY . .

# Запуск dev-сервера
EXPOSE 3001
CMD ["yarn", "dev", "--port", "3001"]